//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaMetrópolis
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoresRecursos
    {
        public int IdRecAutor { get; set; }
        public Nullable<int> IdRec { get; set; }
        public Nullable<int> IdAutor { get; set; }
        public Nullable<bool> EsPrincipal { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Recurso Recurso { get; set; }
    }
}
