//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaMetrópolis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Biblioteca_MetropolisEntities : DbContext
    {
        public Biblioteca_MetropolisEntities()
            : base("name=Biblioteca_MetropolisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<AutoresRecursos> AutoresRecursos { get; set; }
        public virtual DbSet<Editorial> Editorial { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Recurso> Recurso { get; set; }
    }
}
